[tool.poetry]
name = "doc-generator-gui"
version = "0.1.0"
description = "Gerador de termos para empresas."
authors = ["Endryl Richard Monteiro <endrylrm@hotmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
PySide6 = "^6.6.3.1"

[tool.poetry.group.dev.dependencies]
Nuitka = "^2.3.7"
pyinstaller = "^6.8.0"
pytest = "^8.2.2"

[tool.poetry.scripts]
build-nuitka = "src.doc_generator_gui.build:Build_Nuitka"
build-pyinstaller = "src.doc_generator_gui.build:Build_PyInstaller"
main = "src.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
